### ISSUE TITLE
mac电脑识别单词的错误修改

### ISSUE THREAD

**Issue by guaguastandup** [windingwind/bionic-for-zotero#11]
我正在使用v0.06版本的bionic-for-zotero插件，但是它无法正确识别一个单词
例如synchronize这个单词，其中的[syn]和[ron]会被加粗。
我修改了偏移offset，发现它实际上是把[synch]和[ronize]看作了两个单独的词汇。

我在不改动其他部分代码的基础上，修改正则表达式为：
const SEPARATOR_REGEX = /[\p{P}\p{Z}]/u;
获得了期望的效果。

电脑：MacBook Pro 2021
系统：Sonoma 14.4.1
Zotero版本：7.0.9

我理解这个应该是我本地环境的问题
如果有遇到同样问题的人可以试下这个修改

**Comment by windingwind** [comment]
这是因为该PDF的单词中异常地插入有符号类字符匹配`\p{S}`，因此你从正则中去除符号会将被异常分割为两部分的单词重新识别为一个单词。但这是不合理的，因为正常来说单词中间不会出现符号字符。故此关闭该issue，我个人建议不要如此修改。

另，与操作系统无关
